#!/usr/bin/env python3
import sys

n_lines = 10


if len(sys.argv) <2 :
   exit()


if sys.argv[1].startswith("-"):
   n_lines = -1*int(sys.argv[1]) # sys.argv[1][1:]
   filenames=sys.argv[2:]
else:
   filenames=sys.argv[1:]





for filename in filenames:
   print(f"<== {filename} ==> ")
   counter = 0 
   for line in open(filename):
      if counter >= n_lines:
         break
      print(line,end="")
      counter += 1

# Modify it to accept several files
# Files should be seperated by <== FILENAME ==> 
